### ISSUE TITLE
LM3414 Symbol

### ISSUE THREAD

**Issue by BlakeFL** [mikelawrence/RPi-HAT-RGBW-LED-Controller#1]
I noticed your LM3414 symbol pins do not match what is on the datasheet.  I'm new to kicad and wanted to make sure I wasn't missing something when creating my symbol since I'm using your design as a reference.

[http://www.ti.com/ds_dgm/images/alt_snvs678f.gif](url)

**Comment by mikelawrence** [comment]
My symbol pin names and numbers match what is in the datasheet but the pin locations on my schematic symbol do not match the schematic symbol you presented. I swapped pin 3 and 6 on my symbol to make the schematic less confusing. Specifically I didn't like the PWM input on the right side of the symbol. Changes like this are a matter of personal preference. Just so you know this design has been built and is in use.

**Comment by BlakeFL** [comment]
Thanks for the clarification.
